# Generated by Django 4.1 on 2025-04-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='movie_image',
        ),
    ]
